### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iGetUploaded** [rose-dll/Rose-Stealer#239]
**Describe the bug**

**To Reproduce**
When I hit build it loads and then stops loading *green bar* I wait 5ish mins and it still doesn't move

**Screenshots**
![image](https://github.com/rose-dll/Rose-Stealer/assets/54633753/d062d828-1b74-4e3a-a337-90dc2b15c236)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 22

**Additional context**

**Comment by gumbobr0t** [comment]
just wait its compiling...

**Comment by iGetUploaded** [comment]
Got it to finally build but after I run it the console immediately closes and nothing is being logged

**Comment by gumbobr0t** [comment]
send error

**Comment by TheCuteOwl** [comment]
pip install browser_cookie3

**Comment by iGetUploaded** [comment]
I do that and then another one shows up right after.. Basically when they show up I install them and it still just opens & immediately closes

https://github.com/rose-dll/Rose-Stealer/assets/54633753/869da912-d23d-4a9c-8ec8-b16c335f28b1

**Comment by iGetUploaded** [comment]
Tried it multiple times still nothing🤷‍♂️

**Comment by iGetUploaded** [comment]
Update no idea why but its working now 👍
