### ISSUE TITLE
less all

### ISSUE THREAD

**Issue by Lawxsz** [rose-dll/Rose-Stealer#240]
It would be great to reduce the number of modules, many of them are unnecessary and take up more weight and more detections. Example pywifi, getmac, wmi, etc

**Comment by gumbobr0t** [comment]
i know, i am currently rewriting this version and working on a v2.

**Comment by Lawxsz** [comment]
it would be great because it is an excellent grabber, try using os and 1 more module to get everything and it decreases considerably the detections.

**Comment by gumbobr0t** [comment]
> it would be great because it is an excellent grabber, try using os and 1 more module to get everything and it decreases considerably the detections.

thanks, but yeah, i know how python and maldev works. you cant just use os tho, and as i said, im working on a full rewrite only using nodules out the std lib and a v2 in golang.
