### ISSUE TITLE
im back

### ISSUE THREAD

**Issue by yxvi** [rose-dll/Rose-Stealer#241]
hello, i am yuvi not sure you remember me

i am the starter who made you create this project, but you have changed all of the assets to not match my code. I dont have a problem with that, if you forgot i am the creator of Moon Stealer, another variant of W4SP Stealer. 
Add me on discord so we can talk, i am not a enemy i have a friend.

Thanks.

**Comment by yxvi** [comment]
its crazy how this has grown i remember it having 14 stars.

**Comment by yxvi** [comment]
btw this message it to my friend, gumbobrot

**Comment by xpierroz** [comment]
bro is absolutly not the creator of the project and bro have contributed 0 lines to it 🔥🔥

**Comment by gumbobr0t** [comment]
> hello, i am yuvi not sure you remember me
> 
> i am the starter who made you create this project, but you have changed all of the assets to not match my code. I dont have a problem with that, if you forgot i am the creator of Moon Stealer, another variant of W4SP Stealer. 
> Add me on discord so we can talk, i am not a enemy i have a friend.
> 
> Thanks.

haven't we discussed that already yuvi? you just entirely SKIDDED wasp and did not change a single line of code, even tho if you did, we rewrote every single fucking line, so you did nothing for this project except skidding wasp so shut up

**Comment by I-Skid** [comment]
ik but without me in the timeline this wouldn't exist

**Comment by I-Skid** [comment]
who did you get the idea from?

**Comment by I-Skid** [comment]
never said anything about skidding

**Comment by I-Skid** [comment]
if my project didn't exist you wouldn't have gotten the idea to create this

**Comment by I-Skid** [comment]
just saying

**Comment by gumbobr0t** [comment]
bro what? i had the idea to create a stealer even before

**Comment by gumbobr0t** [comment]
> ik but without me in the timeline this wouldn't exist

and it would exist without you, wasp existed before

**Comment by I-Skid** [comment]
blud

**Comment by I-Skid** [comment]
nevermind
