### ISSUE TITLE
are you adding all the features marked later, ive been waiting for them. and is possible to make dualhook?

### ISSUE THREAD

**Issue by Fuydutdtu** [rose-dll/Rose-Stealer#243]
are you adding all the features marked later, ive been waiting for them. and is possible to make dualhook?

**Comment by gumbobr0t** [comment]
no, currently im working on a completely new version of the code.. it will have less features but a large performance increase and better anti-debug + anti-vm, also a web panel.

**Comment by Fuydutdtu** [comment]
ok, have a good day :)
