### ISSUE TITLE
every time i try to test webhook it says webhook failed to execute, then i built file thinking it was just error testing it, but its not, wont send. its not me bc ive tried multiple accs and multiple webhook and muliple server

### ISSUE THREAD

**Issue by Fuydutdtu** [rose-dll/Rose-Stealer#244]
above

**Comment by gumbobr0t** [comment]
send your webhook

**Comment by Fuydutdtu** [comment]
https://discord.com/api/webhooks/1212446520948039770/URO40UnNs_TXSSK1TT_d3WLYjN7VjQpsAoOVf3etmGSJlnz3j4itbJLJcBAffd5ZVmIx

**Comment by gumbobr0t** [comment]
what error do you get when running the file?

**Comment by Fuydutdtu** [comment]
no error, just doesnt send to webhook, the only error i got was when i tested webhook, "webhook failed to execute". ill try on new vm ig

**Comment by gumbobr0t** [comment]
maybe it doesnt work on your vm because you enabled anti debug and/or anti vm??

**Comment by Fuydutdtu** [comment]
that wasnt the problem but i fixed it, but do u have a tutroial on rose RAT?

**Comment by gumbobr0t** [comment]
Rose doesnt work, knight works, look in docs\knight.md

**Comment by gumbobr0t** [comment]
> that wasnt the problem but i fixed it, but do u have a tutroial on rose RAT?
> 

well what was the problem and how did you fix it?
