### ISSUE TITLE
ermmmm why does this try to install a fake windows manager called windowsmanger.exe

### ISSUE THREAD

**Issue by TheMemeManHimself** [rose-dll/Rose-Stealer#250]
![Screenshot 2024-03-26 202617](https://github.com/rose-dll/Rose-Stealer/assets/65554894/05ea61ae-28fd-4c68-b5a5-96c195a9ae18)
kinda weird

**Comment by gumbobrot** [comment]
LMFAOO like it that only the browser script is detected, also the other executable has probably been bound into it or its just your file name. also remove this mcaffee shit and get something good like malwarebytes or kaspersky, even wd is better

**Comment by gumbobrot** [comment]
but if u have concerns check out the code, theres no such script to drop this executable
